networks:
  backend-network:
    driver: bridge

# 定义 secrets，用于构建时传递 settings.xml
# 使用环境变量 MAVEN_SETTINGS_PATH 指定 settings.xml 路径
# Windows: set MAVEN_SETTINGS_PATH=C:\Users\JAM\.m2\settings.xml
# Linux:   export MAVEN_SETTINGS_PATH=$HOME/.m2/settings.xml
secrets:
  settings:
    file: ${MAVEN_SETTINGS_PATH:-~/.m2/settings.xml}

name: atbs

services:
  # 网关服务
  atbs-gateway:
    build:
      context: ..
      dockerfile: atbs-gateway/docker/Dockerfile
      # 构建时挂载 secret
      secrets:
        - settings
    container_name: atbs-gateway
    image: 103.115.43.55:5050/atbs/atbs-gateway:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "8080:8080"
    networks:
      - backend-network


  # 认证服务
  auth-service:
    build:
      context: ..
      dockerfile: auth-service/docker/Dockerfile
      secrets:
        - settings
    container_name: auth-service
    image: 103.115.43.55:5050/atbs/auth-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "8081:8081"
    networks:
      - backend-network


  # 用户服务
  user-service:
    build:
      context: ..
      dockerfile: user-service/docker/Dockerfile
      secrets:
        - settings
    container_name: user-service
    image: 103.115.43.55:5050/atbs/user-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "8082:8082"
    networks:
      - backend-network


  # 订单服务
  order-service:
    build:
      context: ..
      dockerfile: order-service/docker/Dockerfile
      secrets:
        - settings
    container_name: order-service
    image: 103.115.43.55:5050/atbs/order-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "8083:8083"
    networks:
      - backend-network


  # 航班服务
  airplane-service:
    build:
      context: ..
      dockerfile: airplane-service/docker/Dockerfile
      secrets:
        - settings
    container_name: airplane-service
    image: 103.115.43.55:5050/atbs/airplane-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "8084:8084"
    networks:
      - backend-network


  prediction-service:
    build:
      context: ..
      dockerfile: prediction-service/docker/Dockerfile
    container_name: prediction-service
    image: 103.115.43.55:5050/atbs/prediction-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8085:8085"
    networks:
      - backend-network
